language: csharp
mono: none
dist: trusty
dotnet: 1.1.9
solution: Emby.addic7ed.sln
install:
- dotnet restore
script:
- dotnet build -c Release
deploy:
  provider: releases
  api_key:
    secure: HnBTRVu1fiWzoiv0WZwnU1+Jm/UYqtx8bgA80N+3YDc+Q1FhEtF9jE6Da7A8vrapA4jcZBlHhiDnvAaNYx5OK4A2uYffIzXzZkF2Gxd6hYQTwjEPTZC8+1iv3PeVcksDt3GLf3Qf6++8oQcLjbOXvTwvwRu60w4BJUFUJW9y8szfTD3zcCpHplDIKRG8Wj4tnW9yVQ8PPxfzdKEEmaq2g3JZWr/bQWa1G0d6h96j7z5Azx0Mpi46T13hOcoQqrWMhzt1XmK9nD9Z8nq1z8Px7bjrY8Ebm0yPBzTubr9zYf8S7XGoxgOjz6BwItx6Dw+3f814YbZvWEwI0BIzF4x3PPV9WUjw7OYCDxy8y/+B9tVAip86LbkhU6YmGd+F57QWbVDiG9mNNYtAMFtFkdKbSWD1AUF4PKPBnTvvW5r7ZmRxMEzYfvYF569W/otxNb2yY2B7e/0r6bgGN09ypX1zNYq165c5yW8VFTH1wQfI++sh5BUa8D+Kajhj1YgNeWYDh+9iSPWucarS/WS/D+vrG7x0AU0byashIbMyP2fmwfo1RKKeXtufachpNnBXUMoc71GNlxIb6yQ2SYTM6uKhdUn59uSBmAlQdGFxDSQADTJxc4xSUcsbn/3womRXcuWGwn1UITUaJgTteYHe6qyxzOOs0emnoxcjqCYnf8GC60Q=
  file: Emby.addic7ed/bin/Release/netstandard1.3/Emby.addic7ed.dll
  skip_cleanup: true
  on:
    repo: PoppyPop/Emby.addic7ed
    tags: true
